### ISSUE TITLE
cannot loadtest with webrtc over TCP only

### ISSUE THREAD

**Issue by sarunyu** [Softvelum/whep-load-tester#1]
server : mediamtx 1.9.1 
config : 
```
webrtcLocalUDPAddress: ''
webrtcLocalTCPAddress: ':8189'
```

**Comment by alexpokotilo** [comment]
tcp only webrtc version is limited by bandwidth and not use in practice from my POV. If you can easily fix this - please file a pull request. If you cannot, sorry but this is not a big deal for us.

**Comment by alexpokotilo** [comment]
I can accept pull request fixing this, but no plan to fix this myself
